/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "",
    "aws_cognito_identity_pool_id": "",
    "aws_cognito_region": "",
    "aws_user_pools_id": "",
    "aws_user_pools_web_client_id": "",
    "oauth": {},
    aws_cloud_logic: 'enable',
    aws_cloud_logic_custom: [{
        id: '',
        name: '',
        description: 'React Player User Interface API',
        endpoint: '',
        region: '',
        paths: ['/'],
    },
    ],
};


export default awsmobile;
