/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:ec8605d5-d15a-4ee9-9916-1ff09909289d",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_zOtRJ8MXG",
    "aws_user_pools_web_client_id": "6re2urk2vvio7vd5246o9cbd9h",
    "oauth": {},
    aws_cloud_logic: 'enable',
    aws_cloud_logic_custom: [{
        id: 'm4b3f48uni',
        name: 'MediaUserInterfaceAPI',
        description: 'React Player User Interface API',
        endpoint: 'https://m4b3f48uni.execute-api.us-west-2.amazonaws.com/mediaUserInterface',
        region: 'us-west-2',
        paths: ['/'],
    },
    ],
};


export default awsmobile;
